/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class videoconnector_VideoConnecotorJni */

#ifndef _Included_videoconnector_VideoConnecotorJni
#define _Included_videoconnector_VideoConnecotorJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     videoconnector_VideoConnecotorJni
 * Method:    nativeInitialize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_videoconnector_VideoConnecotorJni_nativeInitialize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     videoconnector_VideoConnecotorJni
 * Method:    nativeAddFrame
 * Signature: (F[I)V
 */
JNIEXPORT void JNICALL Java_videoconnector_VideoConnecotorJni_nativeAddFrame
  (JNIEnv *, jobject, jfloat, jintArray);

/*
 * Class:     videoconnector_VideoConnecotorJni
 * Method:    nativeFinalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_videoconnector_VideoConnecotorJni_nativeFinalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
